import { register } from 'node:module';
register('./test-loader.mjs',import.meta.url);
const { api } = await import('./index.mjs');
const { reset,snapshot } = await import('./test-runtime.mjs');
const { credentialKey } = await import('./credentials.mjs');
import { test } from 'node:test';
import assert from 'node:assert/strict';
const student = {id:'s_1',name:'Ученик',role:'student',classId:'c_1',xp:0,currency:1000,level:1,inventory:['av_1'],achievements:[],equipped:{avatar:'av_1',droneColor:'col_default'}};
const teacher = {id:'t_1',name:'Учитель',role:'teacher',password:'old',xp:0,currency:0,level:1,inventory:[],achievements:[],equipped:{avatar:'av_1',droneColor:'col_default'}};
const seed = () => reset({users:{legacyTeacher:teacher,legacyStudent:student,otherTeacher:{...teacher,id:'t_2',name:'Другой'},otherStudent:{...student,id:'s_2',classId:'c_2'}},classrooms:{oldKey:{id:'c_1',name:'Test',teacherId:'t_1',inviteCode:'CODE',studentIds:['s_1']},other:{id:'c_2',name:'Other',teacherId:'t_2',inviteCode:'OTHER',studentIds:['s_2']}}});
const call = (operation,data={},uid) => api({data:{operation,...data},auth:uid ? {uid}:null,rawRequest:{ip:'127.0.0.1',headers:uid ? {authorization:`Bearer ${uid}`}:{}}});
test('API authorization, legacy migration and atomic actions', async () => {
 seed();
 await assert.rejects(call('getUser'),{code:'unauthenticated'});
 await assert.rejects(call('listUsers',{classId:'c_2'},'t_1'),{code:'permission-denied'});
 await assert.rejects(call('deleteClassroom',{classId:'c_1'},'s_1'),{code:'permission-denied'});
 assert.equal((await call('listUsers',{classId:'c_1'},'t_1')).length,1);
 assert.ok(!('password' in await call('getUser',{},'t_1')));
 await assert.rejects(call('login',{role:'teacher',name:'Учитель',password:'wrong'}),{code:'unauthenticated'});
 const logged = await call('login',{role:'teacher',name:' Учитель ',password:'old'});
 assert.equal(logged.token,'test:t_1');
 assert.ok(!snapshot().users.legacyTeacher.password);
 assert.ok(snapshot().credentials[credentialKey('teacher','Учитель')].hash);
 await assert.rejects(call('login',{role:'student',name:'Ученик',inviteCode:'CODE',password:'anything'}),{code:'unauthenticated'});
 const password = await call('resetStudentPassword',{studentId:'s_1'},'t_1');
 assert.equal((await call('login',{role:'student',name:'Ученик',inviteCode:'CODE',password})).token,'test:s_1');
 await assert.rejects(call('resetStudentPassword',{studentId:'s_2'},'t_1'),{code:'permission-denied'});
 const newAccount = await call('login',{role:'teacher',name:'Новый',password:'new-password'});
 const newAccountRetry = await call('login',{role:'teacher',name:'Новый',password:'new-password'});
 assert.equal(newAccount.token,newAccountRetry.token);
 await assert.rejects(call('login',{role:'teacher',name:'Новый',password:'bad-password'}),{code:'unauthenticated'});
 const {default:catalog} = await import('./catalog.json',{with:{type:'json'}});
 const taskId = catalog.tasks[0].id;
 const results = await Promise.all([call('completeTask',{taskId,attempts:0},'s_1'),call('completeTask',{taskId,attempts:0},'s_1'),call('incrementSwitches',{count:2},'s_1')]);
 assert.equal(results.filter(r => r?.awarded).length,1);
 assert.equal(snapshot().users.legacyStudent.suspiciousActivity.totalTabSwitches,2);
 assert.equal(snapshot().users.legacyStudent.completedTaskIds.length,1);
 await assert.rejects(call('completeTask',{taskId:'../../users',attempts:0},'s_1'),{code:'invalid-argument'});
 const map = {gridSize:3,start:[0,0],end:[2,2],obstacles:[]};
 await call('createTask',{classId:'c_1',task:{type:'grid',title:'Custom',description:'Test',mapConfig:map}},'t_1');
 assert.equal((await call('listTasks',{},'s_1')).length,1);
 assert.equal((await call('listTasks',{},'s_2')).length,0);
 await assert.rejects(call('createTask',{classId:'c_1',task:{type:'grid',title:'Bad',description:'Test',mapConfig:{...map,end:[4,4]}}},'t_1'),{code:'invalid-argument'});
 await call('deleteClassroom',{classId:'c_1'},'t_1');
 assert.equal((await call('listClassrooms',{},'s_1')).length,0);
 await assert.rejects(call('listTasks',{},'s_1'),{code:'not-found'});
});
