import React,{useEffect,useState} from 'react';
import type {Task,AssessmentSubmission} from '../types';
import {callServer} from '../services/firebase';
export function AssessmentPanel({classId,onEdit}:{classId:string;onEdit:(task:Task)=>void}){
 const [tasks,setTasks]=useState<Task[]>([]);const [submissions,setSubmissions]=useState<AssessmentSubmission[]>([]);const [selected,setSelected]=useState<string>('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;const refresh=()=>Promise.all([callServer<Task[]>('listTasks',{classId}),callServer<AssessmentSubmission[]>('listSubmissions',{classId})]).then(([t,s])=>{if(alive){setTasks(t.filter(t=>t.assessment));setSubmissions(s);}}).catch(()=>{if(alive)setError('Не удалось загрузить контрольные.');});void refresh();const timer=setInterval(refresh,4000);return()=>{alive=false;clearInterval(timer);};},[classId]);
 const work=submissions.find(s=>s.id===selected);const task=tasks.find(t=>t.id===work?.taskId);
 return <section className="assessment-panel"><h3>Контрольные и ответы</h3>{tasks.length===0&&<p>Контрольных пока нет. Создайте работу в конструкторе.</p>}{tasks.map(t=><article key={t.id}><div className="assessment-question-head"><strong>{t.title}</strong><small>{t.assessment!.published?'Открыта классу':'Черновик / закрыта'}</small></div><div className="assessment-actions"><button onClick={()=>onEdit(t)}>Редактировать</button><button disabled={busy} onClick={async()=>{setBusy(true);try{await callServer('publishAssessment',{classId,taskId:t.id,published:!t.assessment!.published});setTasks(ts=>ts.map(item=>item.id===t.id?{...item,assessment:{...item.assessment!,published:!item.assessment!.published}}:item));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{t.assessment!.published?'Закрыть приём':'Открыть классу'}</button></div><p>Ответов: {submissions.filter(s=>s.taskId===t.id).length}</p>{submissions.filter(s=>s.taskId===t.id).map(s=><button className="assessment-response" key={s.id} onClick={()=>setSelected(s.id)}>{s.studentName} · {Object.values(s.grades).some(g=>g.points===null)?'Нужна проверка':`${Object.values(s.grades).reduce((sum,g)=>sum+(g.points ?? 0),0)} баллов`}</button>)}</article>)}
 {work&&task&&<article className="assessment-review"><div className="assessment-question-head"><h3>{work.studentName} · {task.title}</h3><button onClick={()=>setSelected('')}>Закрыть ответы</button></div>{task.assessment!.questions.map((q,i)=><form key={`${work.id}-${q.id}`} onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);setBusy(true);try{const updated=await callServer<AssessmentSubmission>('reviewSubmission',{submissionId:work.id,questionId:q.id,points:Number(data.get('points')),comment:String(data.get('comment') ?? '')});setSubmissions(ss=>ss.map(s=>s.id===updated.id?updated:s));setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><h4>{i+1}. {q.prompt}</h4><p className="assessment-answer">{q.type==='choice'?q.options?.[Number(work.answers[q.id])]:work.answers[q.id]}</p><p>Текущая оценка: {work.grades[q.id].points ?? 'Ожидает проверки'} / {q.points}</p><label>Баллы за ответ<input name="points" type="number" min={0} max={q.points} step="0.5" defaultValue={work.grades[q.id].points ?? 0} required/></label><label>Комментарий<textarea name="comment" maxLength={2000} defaultValue={work.grades[q.id].comment}/></label><button disabled={busy}>Сохранить оценку</button></form>)}</article>}
 {error&&<p role="alert" className="assessment-error">{error}</p>}</section>;
}
export function AssessmentPlayer({task}:{task:Task}){
 const [answers,setAnswers]=useState<Record<string,string>>({});const [submitted,setSubmitted]=useState<AssessmentSubmission|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{let alive=true;setLoading(true);setAnswers({});setSubmitted(null);setError('');const refresh=()=>callServer<AssessmentSubmission[]>('listSubmissions').then(ss=>{if(alive){setSubmitted(ss.find(s=>s.taskId===task.id) ?? null);setLoading(false);}}).catch(()=>{if(alive){setLoading(false);setError('Не удалось загрузить ответы. Обновите страницу.');}});void refresh();const timer=setInterval(refresh,4000);return()=>{alive=false;clearInterval(timer);};},[task.id]);
 return <section className="assessment-player"><h2>{task.title}</h2><p>{task.description}</p>{loading?<p>Загружаем работу…</p>:submitted?<><h3>Работа отправлена учителю</h3><p>{Object.values(submitted.grades).some(g=>g.points===null)?'Открытые ответы ожидают проверки.':'Все ответы проверены.'} Баллы: {Object.values(submitted.grades).reduce((s,g)=>s+(g.points ?? 0),0)} / {task.assessment!.questions.reduce((s,q)=>s+q.points,0)}</p>{task.assessment!.questions.map((q,i)=><article key={q.id}><h3>{i+1}. {q.prompt}</h3><p className="assessment-answer">{q.type==='choice'?q.options?.[Number(submitted.answers[q.id])]:submitted.answers[q.id]}</p><p>{submitted.grades[q.id].points===null?'Ждёт проверки':`${submitted.grades[q.id].points} / ${q.points} баллов`}</p>{submitted.grades[q.id].comment&&<p>Учитель: {submitted.grades[q.id].comment}</p>}</article>)}</>:<form onSubmit={async e=>{e.preventDefault();if(!window.confirm('Отправить контрольную? После отправки изменить ответы нельзя.'))return;setBusy(true);try{setSubmitted(await callServer('submitAssessment',{taskId:task.id,answers}));setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><p>Ответь на все вопросы. Можно изменить ответы до отправки. После отправки работа сохраняется для проверки.</p>{task.assessment!.questions.map((q,i)=><article key={q.id}><h3>{i+1}. {q.prompt} <small>{q.points} б.</small></h3>{q.type==='choice'?<fieldset><legend>Выбери один ответ</legend>{q.options?.map((o,n)=><label className="assessment-choice" key={n}><input type="radio" name={q.id} required checked={answers[q.id]===String(n)} onChange={()=>setAnswers(a=>({...a,[q.id]:String(n)}))}/>{o}</label>)}</fieldset>:<label>{q.type==='short'?'Короткий ответ':'Твой ответ'}<textarea required maxLength={5000} value={answers[q.id] ?? ''} onChange={e=>setAnswers(a=>({...a,[q.id]:e.target.value}))}/></label>}</article>)}<button className="academy-primary" disabled={busy}>Отправить работу</button></form>}{error&&<p role="alert" className="assessment-error">{error}</p>}</section>;
}
