import { GameButton } from './GameUI';
import React,{useState} from 'react';
import type {AssessmentQuestion,Task} from '../types';
import {callServer} from '../services/firebase';
const fresh=():AssessmentQuestion=>({id:crypto.randomUUID(),type:'choice',prompt:'',points:1,options:['',''],correctIndex:0});
export default function AssessmentBuilder({classId,initial,onClose,onMiniTask}:{classId:string;initial?:Task;onClose:()=>void;onMiniTask:()=>void}){
 const [title,setTitle]=useState(initial?.title ?? '');const [description,setDescription]=useState(initial?.description ?? '');const [questions,setQuestions]=useState<AssessmentQuestion[]>(initial?.assessment?.questions ?? [fresh()]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [preview,setPreview]=useState(false);
 const update=(id:string,change:Partial<AssessmentQuestion>)=>setQuestions(qs=>qs.map(q=>q.id===id?{...q,...change}:q));
 async function save(published:boolean){setBusy(true);setError('');try{await callServer('saveAssessment',{classId,task:{id:initial?.id,title,description,assessment:{published,questions}}});onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="assessment-builder"><header><GameButton size="compact" className="academy-secondary" onClick={onClose}>← Назад</GameButton><h2>Конструктор контрольной</h2><GameButton size="compact" className="academy-secondary" onClick={()=>setPreview(!preview)}>{preview?'Редактировать':'Предпросмотр'}</GameButton></header>
 <p>Работа для выбранного класса. Тесты и короткие ответы проверяются автоматически, развёрнутые ответы — учителем.</p>
 {preview?<><h3>{title||'Название работы'}</h3><p>{description}</p>{questions.map((q,i)=><article key={q.id}><h3>{i+1}. {q.prompt||'Текст вопроса'} <small>{q.points} б.</small></h3>{q.type==='choice'?q.options?.map((o,n)=><p key={n}>○ {o||'Вариант ответа'}</p>):<textarea aria-label={`Предпросмотр ответа ${i+1}`} placeholder={q.type==='short'?'Короткий ответ':'Развёрнутый ответ'} disabled/>}</article>)}</>:<>
 <label>Название работы<input value={title} maxLength={150} onChange={e=>setTitle(e.target.value)} placeholder="Например, проверка по файлам и папкам"/></label><label>Инструкция ученику<textarea value={description} maxLength={3000} onChange={e=>setDescription(e.target.value)} placeholder="Что нужно сделать и на что обратить внимание"/></label>
 {questions.map((q,i)=><article key={q.id}><div className="assessment-question-head"><h3>Вопрос {i+1}</h3><GameButton size="compact" aria-label={`Вопрос ${i+1} выше`} disabled={i===0} onClick={()=>setQuestions(qs=>{const next=[...qs];[next[i-1],next[i]]=[next[i],next[i-1]];return next;})}>↑</GameButton><GameButton size="compact" disabled={questions.length===1} onClick={()=>setQuestions(qs=>qs.filter(item=>item.id!==q.id))}>Удалить</GameButton></div>
 <div className="assessment-fields"><label>Тип вопроса<select value={q.type} onChange={e=>update(q.id,{type:e.target.value as AssessmentQuestion['type'],options:q.options ?? ['',''],correctIndex:q.correctIndex ?? 0})}><option value="choice">Тест с выбором ответа</option><option value="open">Открытый вопрос</option><option value="short">Короткий ответ / минизадача</option></select></label><label>Баллы<input type="number" min={1} max={100} value={q.points} onChange={e=>update(q.id,{points:Number(e.target.value)})}/></label></div>
 <label>Текст вопроса<textarea value={q.prompt} maxLength={3000} onChange={e=>update(q.id,{prompt:e.target.value})}/></label>
 {q.type==='choice'&&<fieldset><legend>Варианты ответа — отметьте правильный</legend>{q.options?.map((o,n)=><div className="assessment-option" key={n}><input type="radio" aria-label={`Правильный вариант ${n+1} вопроса ${i+1}`} name={`correct-${q.id}`} checked={q.correctIndex===n} onChange={()=>update(q.id,{correctIndex:n})}/><input aria-label={`Вариант ${n+1} вопроса ${i+1}`} value={o} maxLength={500} onChange={e=>update(q.id,{options:q.options!.map((v,k)=>k===n?e.target.value:v)})}/><GameButton size="compact" aria-label={`Удалить вариант ${n+1}`} disabled={q.options!.length<=2} onClick={()=>update(q.id,{options:q.options!.filter((_,k)=>k!==n),correctIndex:0})}>×</GameButton></div>)}<GameButton size="compact" disabled={(q.options?.length ?? 0)>=6} onClick={()=>update(q.id,{options:[...(q.options ?? []),'']})}>+ Вариант ответа</GameButton></fieldset>}
 {q.type==='short'&&<><label>Правильный ответ<input value={q.expectedAnswer ?? ''} maxLength={500} onChange={e=>update(q.id,{expectedAnswer:e.target.value})}/></label><small>Сравниваем текст без учёта регистра и лишних пробелов. Например, число или название команды. Баллы можно исправить вручную.</small></>}
 {q.type==='open'&&<small>Ответ ученика сохранится. Вы назначите баллы и оставите комментарий после отправки.</small>}
 </article>)}<GameButton size="compact" disabled={questions.length>=30} onClick={()=>setQuestions(q=>[...q,fresh()])}>+ Добавить вопрос</GameButton></>}
 <p>Всего: {questions.length} вопросов · {questions.reduce((s,q)=>s+q.points,0)} баллов</p>{error&&<p role="alert" className="assessment-error">{error}</p>}
 <footer><GameButton size="compact" disabled={busy} onClick={()=>save(false)}>Сохранить черновик</GameButton><GameButton size="compact" variant="primary" className="academy-primary" disabled={busy} onClick={()=>save(true)}>Открыть классу</GameButton><GameButton size="compact" disabled={busy} onClick={onMiniTask}>Минизадание: маршрут робота</GameButton></footer></section>;
}
