import assert from 'node:assert/strict';
import {cloudOperation,cloudApi} from '../server/cloudBackend';
import type {CloudStore,CloudSnapshot} from '../server/firebaseStore';
let saved:CloudSnapshot|null=null,version=0,conflicts=0;
const store:CloudStore={
 async load(){return {snapshot:structuredClone(saved),etag:String(version)};},
 async save(snapshot,etag){if(conflicts>0){conflicts--;return false;}if(etag!==String(version))return false;saved=structuredClone(snapshot);version++;return true;},
};
process.env.CYBERLEARN_TEACHER_PASSWORD='only-for-cloud-check';
const call=(op:string,data:Record<string,unknown>={},cookie='')=>cloudOperation(store,op,data,cookie,'test-ip');
try {
 const signedOut=await call('getUser');assert.equal(signedOut.error,undefined);assert.equal(signedOut.result,null);
 assert.ok((await call('listClassrooms')).error);
 const teacher=await call('login',{role:'teacher',name:'imyourteacher',password:'only-for-cloud-check'});
 assert.equal(teacher.error,undefined);
 const cookie='cyberlearn_session='+teacher.token;
 assert.ok((await call('login',{role:'teacher',name:'other',password:'only-for-cloud-check'})).error);
 const cls=(await call('createClassroom',{name:'8 А'},cookie)).result as any;
 conflicts=1;
 const student=await call('login',{role:'student',name:'Проверка',inviteCode:cls.inviteCode});
 assert.equal(student.error,undefined);
 const sc='cyberlearn_session='+student.token;
 assert.ok((await call('listUsers',{},sc)).error);
 await call('raiseHand',{raised:true},sc);
 assert.ok(((await call('listUsers',{},cookie)).result as any[])[0].helpRequestedAt);
 const sid=(student.result as any).id;
 assert.ok((await call('sendReaction',{studentId:sid,emoji:'😄'},sc)).error);
 assert.ok((await call('sendReaction',{studentId:sid,emoji:'invalid'},cookie)).error);
 assert.equal((await call('resolveHand',{studentId:sid},cookie)).error,undefined);
 assert.equal((await call('resolveHand',{studentId:sid},cookie)).error,undefined);
 assert.equal((await call('sendReaction',{studentId:sid,emoji:'😄'},cookie)).error,undefined);
 assert.equal((await call('sendReaction',{studentId:sid,emoji:'💩'},cookie)).error,undefined);
 const feedback=(await call('receiveFeedback',{},sc)).result as any[];
 assert.deepEqual(feedback.map(f=>f.kind),['help','reaction','reaction']);
 assert.deepEqual(feedback.slice(1).map(f=>f.emoji),['😄','💩']);
 assert.equal(new Set(feedback.map(f=>f.id)).size,3);
 assert.deepEqual((await call('receiveFeedback',{},sc)).result,[]);
 assert.ok((await call('receiveFeedback',{},cookie)).error);
 const usersBefore=Object.keys(saved!.state.users).length;
 const again=await call('login',{role:'student',name:'Проверка',inviteCode:cls.inviteCode});
 assert.equal((again.result as any).id,(student.result as any).id);
 assert.equal(Object.keys(saved!.state.users).length,usersBefore);
 assert.equal(Object.values(saved!.state.users).filter(u=>u.role==='teacher').length,1);
 const otherClass=(await call('createClassroom',{name:'8 Б'},cookie)).result as any;
 const otherStudent=await call('login',{role:'student',name:'Другой',inviteCode:otherClass.inviteCode});
 const otherCookie='cyberlearn_session='+otherStudent.token;
 assert.ok((await call('endClassSession',{classId:cls.id},sc)).error);
 assert.ok((await call('removeClassStudent',{classId:cls.id,studentId:(student.result as any).id},sc)).error);
 saved!.state.classes[otherClass.id].teacherId='another_teacher';
 assert.ok((await call('endClassSession',{classId:otherClass.id},cookie)).error);
 assert.ok((await call('removeClassStudent',{classId:otherClass.id,studentId:(otherStudent.result as any).id},cookie)).error);
 saved!.state.classes[otherClass.id].teacherId=(teacher.result as any).id;
 assert.ok((await call('removeClassStudent',{classId:cls.id,studentId:(otherStudent.result as any).id},cookie)).error);
 const originalCode=saved!.state.classes[cls.id].inviteCode;
 const legacyId=(student.result as any).id;
 delete saved!.state.users[legacyId].classId; // Legacy membership exists only in studentIds.
 assert.equal((await call('endClassSession',{classId:cls.id},cookie)).error,undefined);
 assert.equal(saved!.state.classes[cls.id].inviteCode,originalCode,'Ending sessions must preserve the class code');
 assert.equal((await call('getUser',{},sc)).result,null);
 assert.ok((await call('listTasks',{},sc)).error);
 assert.equal((await call('getUser',{},'cyberlearn_session='+again.token)).result,null);
 assert.ok((await call('getUser',{},otherCookie)).result);
 assert.ok((await call('getUser',{},cookie)).result);
 saved!.state.users[legacyId].classId=cls.id;
 const folderChange=await call('setClassFolder',{classId:cls.id,folder:'  Школа 2  '},cookie);
 assert.equal((folderChange.result as any).folder,'Школа 2');
 assert.equal(saved!.state.classes[cls.id].inviteCode,originalCode);
 const returned=await call('login',{role:'student',name:'Проверка',inviteCode:cls.inviteCode});
 assert.equal((returned.result as any).id,(student.result as any).id);
 const returnedAgain=await call('login',{role:'student',name:'Проверка',inviteCode:cls.inviteCode});
 assert.equal((await call('removeClassStudent',{classId:cls.id,studentId:(student.result as any).id},cookie)).error,undefined);
 assert.equal((await call('getUser',{},'cyberlearn_session='+returned.token)).result,null);
 assert.equal((await call('getUser',{},'cyberlearn_session='+returnedAgain.token)).result,null);
 assert.equal(saved!.state.users[(student.result as any).id].classId,undefined);
 assert.ok(!saved!.state.classes[cls.id].studentIds.includes((student.result as any).id));
 assert.equal(((await call('listUsers',{classId:cls.id},cookie)).result as any[]).length,0);
 const fresh=await call('login',{role:'student',name:'Проверка',inviteCode:cls.inviteCode});
 assert.notEqual((fresh.result as any).id,(student.result as any).id);
 const activeSession=Object.values(saved!.sessions).find(s=>s.uid===(teacher.result as any).id)!;
 activeSession.expires=Date.now()-1;
 const expired=await call('getUser',{},cookie);assert.equal(expired.error,undefined);assert.equal(expired.result,null);
 assert.ok((await call('listClassrooms',{},cookie)).error);
 assert.ok(Object.values(saved!.state.credentials).every(c=>c.digest && !JSON.stringify(c).includes('only-for-cloud-check')));
 let output='',status=0;
 const res:any={setHeader(){},set statusCode(n:number){status=n;},end(s:string){output=s;}};
 await cloudApi({method:'POST',headers:{host:'cyberlearn.example',origin:'https://other.example'},body:{operation:'getUser'}},res);
 assert.equal(status,403);assert.ok(JSON.parse(output).error);
 await cloudApi({method:'GET',headers:{}},res);assert.equal(status,405);
 console.log('cloudBackend.check: one teacher, class-code entry, private class access, hand requests, retry on write conflict, session and credential persistence, and HTTP guards.');
} finally {delete process.env.CYBERLEARN_TEACHER_PASSWORD;}
