import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {localApi,provisionTeacher} from '../server/localBackend';
const previous=process.cwd();const dir=mkdtempSync(join(tmpdir(),'cyberlearn-school-'));process.chdir(dir);
await provisionTeacher('imyourteacher','test-teacher-secret');
const server=createServer((req,res)=>localApi(req,res,()=>{res.statusCode=404;res.end();}));
await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));
const port=(server.address() as {port:number}).port;
async function call(operation:string,data:Record<string,unknown>={},cookie='') {
 const r=await fetch(`http://127.0.0.1:${port}/api/local`,{method:'POST',headers:{'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({operation,...data})});
 return {status:r.status,cookie:r.headers.get('set-cookie')?.split(';')[0] ?? '',...await r.json()};
}
try {
 assert.equal((await call('login',{role:'teacher',name:'intruder',password:'test-teacher-secret'})).status,400);
 assert.equal((await call('login',{role:'teacher',name:'imyourteacher',password:'bad-secret'})).status,400);
 const teacher=await call('login',{role:'teacher',name:'imyourteacher',password:'test-teacher-secret'});assert.equal(teacher.status,200);assert.ok(teacher.cookie);
 await call('createFolder',{name:'Школа № 1'},teacher.cookie);await call('createFolder',{name:'Школа № 2'},teacher.cookie);
 const c1=(await call('createClassroom',{name:'3 А'},teacher.cookie)).data;
 const c2=(await call('createClassroom',{name:'3 А'},teacher.cookie)).data;
 await call('updateClassroom',{classroom:{...c1,folder:'Школа № 1'}},teacher.cookie);
 await call('updateClassroom',{classroom:{...c2,folder:'Школа № 2'}},teacher.cookie);
 assert.notEqual(c1.inviteCode,c2.inviteCode);
 assert.equal((await call('login',{role:'student',name:'Саша',inviteCode:'INVALID'})).status,400);
 const student=await call('login',{role:'student',name:'Саша',inviteCode:c1.inviteCode});assert.equal(student.status,200);
 assert.equal((await call('listUsers',{},student.cookie)).status,400);
 assert.equal((await call('updateClassroom',{classroom:c1},student.cookie)).status,400);
 assert.equal((await call('createFolder',{name:'hack'},student.cookie)).status,400);
 assert.equal((await call('raiseHand',{raised:true},student.cookie)).status,200);
 const users=(await call('listUsers',{},teacher.cookie)).data;assert.ok(users[0].helpRequestedAt);
 assert.equal((await call('resolveHand',{studentId:users[0].id},student.cookie)).status,400);
 await call('resolveHand',{studentId:users[0].id},teacher.cookie);
 assert.equal((await call('getUser',{},student.cookie)).data.helpRequestedAt,undefined);
 const again=await call('login',{role:'student',name:'Саша',inviteCode:c1.inviteCode});assert.equal(again.data.id,student.data.id);
 const sameName=await call('login',{role:'student',name:'Саша',inviteCode:c2.inviteCode});assert.notEqual(sameName.data.id,student.data.id);
 const classes=(await call('listClassrooms',{},teacher.cookie)).data;assert.deepEqual(classes.map((c:any)=>c.folder),['Школа № 1','Школа № 2']);
 const questions=[{id:'q1',type:'choice',prompt:'Выбери папку',points:2,options:['Папка','Файл'],correctIndex:0},{id:'q2',type:'short',prompt:'2 + 2',points:1,expectedAnswer:'4'},{id:'q3',type:'open',prompt:'Объясни ответ',points:3}];
 const assessment=(await call('saveAssessment',{classId:c1.id,task:{title:'Проверка',assessment:{published:false,questions}}},teacher.cookie)).data;
 assert.ok(assessment?.id);
 assert.equal((await call('listTasks',{},student.cookie)).data.length,0);
 assert.equal((await call('saveAssessment',{classId:c1.id,task:{title:'hack',assessment:{published:true,questions}}},student.cookie)).status,400);
 await call('publishAssessment',{classId:c1.id,taskId:assessment.id,published:true},teacher.cookie);
 const visible=(await call('listTasks',{},student.cookie)).data[0];assert.equal(visible.assessment.questions[0].correctIndex,undefined);assert.equal(visible.assessment.questions[1].expectedAnswer,undefined);
 assert.equal((await call('submitAssessment',{taskId:assessment.id,answers:{q1:'0'}},student.cookie)).status,400);
 assert.equal((await call('submitAssessment',{taskId:assessment.id,answers:{q1:'0',q2:'4',q3:'Ответ'}},sameName.cookie)).status,400);
 const answer=(await call('submitAssessment',{taskId:assessment.id,answers:{q1:'0',q2:' 4 ',q3:'Ответ'}},student.cookie)).data;
 assert.equal(answer.grades.q1.points,2);assert.equal(answer.grades.q2.points,1);assert.equal(answer.grades.q3.points,null);
 assert.equal((await call('submitAssessment',{taskId:assessment.id,answers:{q1:'0',q2:'4',q3:'Ответ'}},student.cookie)).status,400);
 assert.equal((await call('reviewSubmission',{submissionId:answer.id,questionId:'q3',points:3},student.cookie)).status,400);
 assert.equal((await call('reviewSubmission',{submissionId:answer.id,questionId:'q3',points:4},teacher.cookie)).status,400);
 assert.equal((await call('saveAssessment',{classId:c1.id,task:{...assessment,assessment:{published:true,questions}}},teacher.cookie)).status,400);
 const reviewed=(await call('reviewSubmission',{submissionId:answer.id,questionId:'q3',points:2,comment:'Хорошо'},teacher.cookie)).data;assert.equal(reviewed.grades.q3.points,2);
 assert.equal((await call('listSubmissions',{},sameName.cookie)).data.length,0);
 assert.equal((await call('listSubmissions',{},student.cookie)).data[0].grades.q3.comment,'Хорошо');
 await call('publishAssessment',{classId:c1.id,taskId:assessment.id,published:false},teacher.cookie);assert.equal((await call('listTasks',{},student.cookie)).data.length,1);
 const newcomer=await call('login',{role:'student',name:'Другой ученик',inviteCode:c1.inviteCode});assert.equal((await call('listTasks',{},newcomer.cookie)).data.length,0);
 await call('logout',{},student.cookie);assert.equal((await call('getUser',{},student.cookie)).status,400);
 assert.ok(!readFileSync('.cyberlearn/data.json','utf8').includes('test-teacher-secret'));
 console.log('School server: teacher-only login, sessions, permissions, folders, help, assessment publication, hidden answers, grading, review and permissions passed.');
}finally{await new Promise<void>(r=>server.close(()=>r()));process.chdir(previous);rmSync(dir,{recursive:true,force:true});}
