import assert from 'node:assert/strict';
import { completeTask, buyCosmetic, validateMap, publicUser } from '../functions/domain.mjs';
import { COSMETICS, MOCK_TASKS, LEVEL_THRESHOLDS, ACHIEVEMENTS } from '../constants';
import { checkShell, terminalLanguage } from '../services/terminal';
import { evaluateSumFormula, parseIfFormula } from '../services/spreadsheetEvaluation';
import { readStoredJSON } from '../utils/storage';
const catalog = { tasks:MOCK_TASKS, cosmetics:COSMETICS, levels:LEVEL_THRESHOLDS, achievements:ACHIEVEMENTS };
const user = {id:'s_test',name:'Test',role:'student',xp:0,currency:1000,level:5,inventory:['av_1'],achievements:[],equipped:{avatar:'av_1',droneColor:'col_default'},taskAttempts:[{taskId:'other'}],suspiciousActivity:{totalTabSwitches:12,highErrorTasks:[]}};
const task = MOCK_TASKS[0];
const first = completeTask(user,task,0,catalog,new Date('2026-10-02T10:00:00Z'));
const duplicate = completeTask(first.user,task,0,catalog);
assert.equal(duplicate.awarded,false);
assert.equal(duplicate.user.xp,first.user.xp);
assert.deepEqual(first.user.taskAttempts,user.taskAttempts);
assert.equal(first.user.suspiciousActivity.totalTabSwitches,12);
assert.equal(first.user.lastActiveDate,'2026-10-02');
const second = completeTask(first.user,MOCK_TASKS[1],0,catalog,new Date('2026-10-03T10:00:00Z'));
assert.equal(second.user.streak,2);
const free = {...task,id:'free',currencyReward:0};
assert.equal(completeTask(user,free,0,catalog).user.currency,user.currency);
assert.throws(() => completeTask(user,task,-1,catalog));
const item = COSMETICS.find(i => i.cost > 0 && i.unlockLevel <= first.user.level)!;
const bought = buyCosmetic(first.user,item);
assert.deepEqual(bought.completedTaskIds,first.user.completedTaskIds);
assert.equal(bought.taskAttempts.length,1);
assert.equal(bought.currency,first.user.currency-item.cost);
assert.throws(() => buyCosmetic(bought,item));
assert.throws(() => buyCosmetic(user,COSMETICS.find(i => !user.inventory.includes(i.id)),true));
assert.ok(!('password' in publicUser({...user,password:'secret'})));
validateMap({gridSize:3,start:[0,0],end:[2,2],obstacles:[]});
assert.throws(() => validateMap({gridSize:3,start:[0,0],end:[4,4],obstacles:[]}));
assert.throws(() => validateMap({gridSize:3,start:[0,0],end:[2,2],obstacles:[[0,1],[1,0]]}));
assert.equal(evaluateSumFormula('=SUM(D2:D4)',[300,200,500]),1000);
assert.equal(evaluateSumFormula('=D2-D3-D4',[300,200,500]),null);
assert.equal(evaluateSumFormula('=SUM(D2:D4)+99',[300,200,500]),null);
assert.equal(parseIfFormula('=IF(B2>60; "СДАЛ"; "ПЕРЕСДАЧА")')?.inclusive,false);
assert.equal(parseIfFormula('=IF(B2>=60; "СДАЛ"; "ПЕРЕСДАЧА")')?.inclusive,true);
assert.equal(parseIfFormula('=IF(B3>=60; "СДАЛ"; "ПЕРЕСДАЧА")'),null);
const shellTasks = MOCK_TASKS.filter(t => t.type === 'terminal' && terminalLanguage(t) === 'shell');
for (const t of shellTasks) {
 assert.ok(checkShell(t.initialCode!,t));
 assert.throws(() => checkShell('print("anything")',t),t.id);
}
(globalThis as any).localStorage = {getItem:() => '{broken'};
assert.deepEqual(readStoredJSON('broken',{}),{});
(globalThis as any).localStorage = {getItem:() => 'null'};
assert.deepEqual(readStoredJSON('broken',{}),{});
console.log(`regressions.check: transactions, retry idempotency, streaks, maps, formulas, storage and ${shellTasks.length} shell lessons OK`);
